
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required

before_install:
    - sudo sed -i 's|xenial|bionic|g' /etc/apt/sources.list
    - sudo apt-key --keyring /etc/apt/trusted.gpg.d/whonix.gpg adv --keyserver hkp://ipv4.pool.sks-keyservers.net:80 --recv-keys 916B8D99C38EAF5E8ADC7A2A8D66066A2EEACCDA
    - echo 'deb http://deb.whonix.org stretch-testers main' | sudo tee /etc/apt/sources.list.d/whonix.list
    - sudo apt-get update
    - sudo apt-get dist-upgrade
    - sudo apt-get install genmkfile ruby-ronn debhelper make

script:
    - make deb

install:
    - make deb
