Document: i2p-ssh-config
Title: Debian i2p-ssh-config Manual
Author: <insert document author here>
Abstract: This manual describes what i2p-ssh-config is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/i2p-ssh-config/i2p-ssh-config.sgml.gz

Format: postscript
Files: /usr/share/doc/i2p-ssh-config/i2p-ssh-config.ps.gz

Format: text
Files: /usr/share/doc/i2p-ssh-config/i2p-ssh-config.text.gz

Format: HTML
Index: /usr/share/doc/i2p-ssh-config/html/index.html
Files: /usr/share/doc/i2p-ssh-config/html/*.html
