#!/bin/sh
set -e
# Automatically added by dh_installsystemd/11.5.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'i2p-ssh.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'i2p-ssh.service' >/dev/null || true
		deb-systemd-helper unmask 'i2p-ssh.service' >/dev/null || true
	fi
fi
# End automatically added section
